---
containerNames:
  - frontend
serverIndexFile: index.html
fetchTodosScriptFile: fetchTodos.js
serviceName: frontend-svc
clusterPort: 1010
appPort: 3010
depValues:
  project:
    apps:
      backend:
        - containerNames
    initjobs:
      picturefetcher:
        - randomPictureFileName
