---
containerNames:
  - frontend
serverIndexFile: index.html
fetchTodosScriptFile: fetchTodos.js
serviceName: frontend-svc
clusterPort: 1010
appPort: 3010
probePath: /healthz
depValues:
  project:
    apps:
      backend:
        - containerNames
        - serviceName
        - clusterPort
      imagefile:
        - containerNames
        - serviceName
        - clusterPort
