---
{{- with .Values}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{index .containerNames 0}}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: {{index .containerNames 0}}
        spec:
          restartPolicy: OnFailure
          containers:
              {{- include "container.base" $ | indent 4}}
              {{- include "security.context" $ | indent 4}}
              {{- include "volumemounts.base" $ | indent 4}}
                - name: {{.sharedPersistentVolumeName}}
                  mountPath: {{.sharedVolumeMountPath}}
                  readOnly: false
            {{- include "volumes.base" $ | indent 4}}
            - name: {{.sharedPersistentVolumeName}}
              persistentVolumeClaim:
                claimName: {{.sharedPersistentVolumeClaimName}}
{{- end}}
