---
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#horizontalpodautoscaler-v2-autoscaling
{{- with .Values}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{index .containerNames 0}}-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{index .containerNames 0}}
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
{{- end}}
