---
{{- with .Values}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{index .containerNames 0}}-ingress
spec:
  rules:
    - host: {{index .containerNames 0}}
    - http:
        paths:
          - path: /{{index .containerNames 0}}
            pathType: Prefix
            backend:
              service:
                name: {{.serviceName}}
                port:
                  number: {{.clusterPort}}
{{- end}}
