---
{{- with .Values}}
{{- template "deployment.spec.base" $}}
    spec:
      containers:
          {{- template "container.base" $}}
          {{- template "postgres.env" $}}
          ports:
            - containerPort: {{.appPort}}
          {{- template "probes.get" $}}
          {{- template "security.context" $}}
          {{- template "volumemounts.base" $}}
      {{- template "volumes.base" $}}
      terminationGracePeriodSeconds: 5
{{- end}}
