---
{{- with .Values}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{index .containerNames 0}}
data:
  {{index .containerNames 0}}: |
    #!/bin/bash
    set -euo pipefail

    PYTHONPATH=/app /app/pingpong/pingpong.py \
    --port "{{.pingPongAppPort}}" \
    --counter-file "{{.pongFileMountPath}}/{{.pongFileName}}"
{{- end }}
