simpleServerAppName: simple-server
simpleServerAppServiceName: simple-server-svc
simpleServerAppClusterPort: 1010
simpleServerAppPort: 3010
pingPongAppName: pingpong
pingPongAppServiceName: pingpong-svc
pingPongAppClusterPort: 1020
pingPongAppPort: 3020
randomLogServerAppName: random-log-server
randomLogServerAppServiceName: random-log-server-svc
randomLogServerAppClusterPort: 1030
randomLogServerAppPort: 3030
