apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.projectAppServiceName}}
                port:
                  number: {{.Values.projectAppClusterPort}}
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: {{.Values.pingPongAppServiceName}}
                port:
                  number: {{.Values.pingPongAppClusterPort}}
          - path: /randomlog
            pathType: Prefix
            backend:
              service:
                name: {{.Values.randomLogServerAppServiceName}}
                port:
                  number: {{.Values.randomLogServerAppClusterPort}}
