apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.sharedPersistentVolumeClaimName}}
spec:
  storageClassName: {{.Values.sharedPersistentVolumeName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
