---
{{- with .Values}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{index .containerNames 0}}
spec:
  serviceName: {{.serviceName}}
  replicas: 1
  selector:
    matchLabels:
      app: {{index .containerNames 0}}
  template:
    metadata:
      labels:
        app: {{index .containerNames 0}}
    spec:
      containers:
        - name: {{index .containerNames 0}}
          image: "{{.imageRegistry}}/{{index .containerNames 0}}:latest"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: {{index .containerNames 0}}
            - configMapRef:
                name: {{index .containerNames 0}}
          ports:
            - containerPort: {{.appPort}}
          readinessProbe:
            tcpSocket:
              port: {{.appPort}}
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: {{.dbVolumeName}}
              mountPath: {{.dbMountPath}}
              readOnly: false
              subPath: {{index .containerNames 0}}
  volumeClaimTemplates:
    - metadata:
        name: {{.dbVolumeName}}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{.storageClassName}}
        resources:
          requests:
            storage: 100Mi
{{- end}}
