#!/usr/bin/env python3

"""Simple server tool."""

import http.server
import socketserver
import sys
from pathlib import Path


class ProjectRequestHandler(http.server.SimpleHTTPRequestHandler):
    """Request handler that serves the content of a log file."""

    def do_GET(self) -> None:  # noqa: N802
        """Handle GET requests by reading the log file and returning its content."""
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        index_file = Path("{{.tempScriptVolumeMountPath}}/{{.serverindexFile}}")
        with index_file.open("r") as file:
            self.wfile.write(file.read().encode("utf-8"))


class ProjectServer:
    """Server to handle project requests."""

    @staticmethod
    def run(port: int) -> None:
        """Start the server."""
        with socketserver.TCPServer(("", port), ProjectRequestHandler) as httpd:
            sys.stdout.write(f"Server started in port {port}\n")
            sys.stdout.flush()
            httpd.serve_forever()


if __name__ == "__main__":
    ProjectServer.run(int("{{.projectAppPort}}"))
