---
containerNames:
  - backend
  - backend-debug
serviceName: backend-svc
clusterPort: 1015
appPort: 3015
dbTableName: todos
depValues:
  project-common:
    databases:
      postgres:
        - serviceName
        - appPort
        - containerNames
