apiVersion: ENC[AES256_GCM,data:+4Q=,iv:Ixh4Vj83xehUT+aVqMcTmeTGSMB5a6BUBrpBc3+GAQY=,tag:MSyPBLRXFAFNQQfodqAf4w==,type:str]
kind: ENC[AES256_GCM,data:mPbvrA3z,iv:DTPEoJAV14TY6sD9EqGUycslurTWoW7v99Po/hTx+CY=,tag:+OG+quKKky5TBNcsE8i1Aw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xk42aMSy9n0=,iv:+iKzo1UgFNVF+PE7qvVhUcHi3TxRjC35HbDT8L8xYHY=,tag:7/0DDL5/wY4uo/UN/UCBPA==,type:str]
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:mNsnZxHyNoWJu55bj+9GNXL4MLw7zq2t,iv:4WPR1/uXmBHORYTAG/Q7KRxUWplGjXnuzqnjU4ip6Is=,tag:Vk8hEmLCfGzaES1+GuBVQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19m0dxydhg0j5ymwupnh9erf4z9umyqed7dex88sxrmahr5yfgc7qdlch2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0N3ZUc2JZYTNyZXdWampi
            a0REREhBL2hWYWJsYTBNdnZHK2RXMm5tdUFVClFhaytsYnorSHk5OXFRTmZxVDZU
            U1VaQXhUZFJrcVRITXFCM1doWkcrcDQKLS0tIEdBbzRBd2g5QUxnODJmMjFpci9s
            T0Z6VWlwWWdOVjBuM2cwb29wQVlSbVkKcDLtX3HksuJsz/U+ukJ5OwtDxU19ibhS
            NzK5LvH112GH72lWxMwlsT3rIvez+wCw3CfZKYH4m2ECQmUA0wQ7HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T18:10:54Z"
    mac: ENC[AES256_GCM,data:zUiUwV0ugFA0XDY6Iw7jb4D7rdIQgUHZ8C2swyfkwJAL+++eybtYhx3Y+BFnhCfZt9xqjxCZ2bERlIEk9dOuj8RPkI9s0B96u+EXOwo5CPs2uhv3BBoAHnz2WYOFj65BCBewtHo1BOoYS0M+JxikDViRXWssy916dOYzl2AFAZg=,iv:HUEVT69DSRZPpMfGvgOBQ+uUmXBjJHd4KlVKiVDD36k=,tag:9wCBW+I//RgzIa3S8F/W/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
