#!/usr/bin/env python3
"""Serves files."""

import socketserver
import sys
from http.server import SimpleHTTPRequestHandler


class FileServer:
    """Server to handle ping-pong requests."""

    @staticmethod
    def run(port: int) -> None:
        """Start the server."""
        with socketserver.TCPServer(("", port), SimpleHTTPRequestHandler) as httpd:
            sys.stdout.write(f"Server started in port {port}\n")
            sys.stdout.flush()
            httpd.serve_forever()


if __name__ == "__main__":
    FileServer.run(int("{{.appPort}}"))
