apiVersion: v1
kind: Service
metadata:
  name: {{.Values.pingPongAppServiceName}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.pingPongAppName}}
  ports:
    - port: {{.Values.pingPongAppClusterPort}}
      protocol: TCP
      targetPort: {{.Values.pingPongAppPort}}
