---
{{- with .Values}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{index .containerNames 0}}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: {{index .containerNames 0}}
        spec:
          restartPolicy: OnFailure
          containers:
              {{- include "container.base" $ | indent 4}}
              envFrom:
                - secretRef:
                    name: {{index .apps.postgres.containerNames 0}}
              {{- include "security.context" $ | indent 4}}
              {{- include "volumemounts.base" $ | indent 4}}
          {{- include "volumes.base" $ | indent 4}}
{{- end}}
