---
containerNames:
  - imagefile
serviceName: imagefile-svc
clusterPort: 1016
appPort: 3016
probePath: /healthz
depValues:
  project-common:
    databases:
      postgres:
        - serviceName
        - appPort
        - containerNames
depValuesNoRoute:
  project:
    jobs:
      picturefetcher:
        - dbItemId
        - dbTableName
