---
containerNames:
  - imagefile
serviceName: imagefile-svc
clusterPort: 1016
appPort: 3016
probePath: /healthz
depValues:
  project-other:
    databases:
      postgres:
        - serviceName
        - appPort
        - containerNames
depValuesNoRoute:
  project:
    initjobs:
      picturefetcher:
        - dbItemId
        - dbTableName
