---
name: Delete branch
description: Delete deployments related to branch
inputs:
  project:
    description: "The project to delete"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |-
        full_ref="${{ github.event.ref }}"
        export GITHUB_EVENT_REF="${full_ref#refs/heads/}"
        tools/gh-workflows/delete_branch_namespace.sh "${{ inputs.project }}"
