---
{{- with .Values}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{index .containerNames 0}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{index .containerNames 0}}
  template:
    metadata:
      labels:
        app: {{index .containerNames 0}}
    spec:
      containers:
        - name: {{index .containerNames 0}}
          image: "{{index .containerNames 0}}:latest"
          imagePullPolicy: IfNotPresent
          resources: &resource_limits
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          command:
            - "/bin/bash"
            - "-c"
            - "{{.tempScriptVolumeMountPath}}/{{index .containerNames 0}}"
          readinessProbe:
            httpGet:
              path: /
              port: {{.appPort}}
              httpHeaders:
                - name: Content-Type
                  value: text/plain
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - &logfile_mount
              name: {{.logFileVolumeName}}
              mountPath: {{.logFileMountPath}}
            - &temp_script_mount
              name: {{.tempStartupScriptVolumeName}}
              mountPath: {{.tempScriptVolumeMountPath}}
              readOnly: true
        - name: {{index .containerNames 1}}
          image: "{{index .containerNames 1}}:latest"
          imagePullPolicy: IfNotPresent
          resources: *resource_limits
          command:
            - "/bin/bash"
            - "-c"
            - "{{.tempScriptVolumeMountPath}}/{{index .containerNames 1}}"
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{index .containerNames 0}}
                  key: MESSAGE
          readinessProbe:
            exec:
              command:
                - cat
                - "{{.logFileMountPath}}/{{.logFileName}}"
          volumeMounts:
            - *logfile_mount
            - *temp_script_mount
      volumes:
        - name: {{.logFileVolumeName}}
          emptyDir: {}
        - name: {{.tempStartupScriptVolumeName}}
          configMap:
            name: {{index .containerNames 0}}
            items:
              - key: {{index .containerNames 0}}
                path: {{index .containerNames 0}}
                mode: 0755
              - key: {{index .containerNames 1}}
                path: {{index .containerNames 1}}
                mode: 0755
              - key: {{.informationFile}}
                path: {{.informationFile}}
{{- end}}
