---
{{- with .Values}}
{{- include "deployment.spec.base" $}}
    spec:
      {{- include "init.container.waitdb" $}}
      containers:
          {{- include "container.base" $}}
          ports:
            - containerPort: {{.appPort}}
          {{- include "probes.get" $}}
          {{- include "security.context" $}}
          {{- include "volumemounts.base" $}}
            - &logfile_mount
              name: {{.logFileVolumeName}}
              mountPath: {{.logFileMountPath}}
        - name: {{index .containerNames 1}}
          image: "{{.imageRegistry}}/{{index .containerNames 1}}:{{.versionTag}}"
          imagePullPolicy: {{.imagePullPolicy}}
          resources: *resource_limits
          command:
            - "/bin/bash"
            - "-c"
            - "{{.tempScriptVolumeMountPath}}/{{index .containerNames 1}}"
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{index .containerNames 0}}
                  key: MESSAGE
          envFrom:
            - secretRef:
                name: {{index .databases.postgres.containerNames 0}}
          readinessProbe:
            exec:
              command:
                - cat
                - "{{.logFileMountPath}}/{{.logFileName}}"
          {{- include "security.context" $}}
          {{- include "volumemounts.base" $}}
            - *logfile_mount
      {{- include "volumes.base" $}}
        - name: {{.logFileVolumeName}}
          emptyDir: {}
      terminationGracePeriodSeconds: 5
{{- end}}
