#!/usr/bin/env python3

"""Simple server tool."""

import http.server
from pathlib import Path

from tcpserver import TCPServerLauncher


class RequestHandler(http.server.SimpleHTTPRequestHandler):  # noqa: D101
    JS_SCRIPT_PATH = "{{.tempScriptVolumeMountPath}}/{{.fetchTodosScriptFile}}"

    def do_GET(self) -> None:  # noqa: N802
        """Handle GET requests by reading the log file and returning its content."""
        if self.path.endswith(self.JS_SCRIPT_PATH):
            self._handle_scriptfile()
        elif self.path.endswith("/healthz"):
            self.send_response(200)
            self.end_headers()
        else:
            self._handle_frontpage()

    def _handle_frontpage(self) -> None:
        index_file = Path("{{.tempScriptVolumeMountPath}}/{{.serverIndexFile}}")
        with index_file.open("r") as file:
            file_content = file.read().encode("utf-8")
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(file_content)

    def _handle_scriptfile(self) -> None:
        script_file = Path(self.JS_SCRIPT_PATH)
        with script_file.open("r") as file:
            file_content = file.read().encode("utf-8")
        self.send_response(200)
        self.send_header("Content-type", "application/javascript")
        self.end_headers()
        self.wfile.write(file_content)


if __name__ == "__main__":
    TCPServerLauncher.run(int("{{.appPort}}"), RequestHandler)
