---
containerNames:
  - logserver
  - printer
logFileMountPath: /logfile
logFileName: logfile.log
logFileVolumeName: logfile-volume
serviceName: logserver-svc
clusterPort: 1030
appPort: 3030
informationFile: information.txt
depValues:
  project-common:
    databases:
      postgres:
        - serviceName
        - appPort
        - containerNames
  project-other:
    apps:
      pingpong:
        - serviceName
        - clusterPort
        - containerNames
depValuesNoRoute:
  project-other:
    apps:
      pingpong:
        - dbTableName
        - dbCounterTableItemId
