apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.simpleServerAppServiceName }}
            port:
              number: {{ .Values.simpleServerAppClusterPort }}
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.pingPongAppServiceName }}
            port:
              number: {{ .Values.pingPongAppClusterPort }}
      - path: /randomlog
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.randomLogServerAppServiceName }}
            port:
              number: {{ .Values.randomLogServerAppClusterPort }}
