apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.simpleServerAppServiceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.simpleServerAppName }}
  ports:
    - port: {{ .Values.simpleServerAppClusterPort }}
      protocol: TCP
      targetPort: {{ .Values.simpleServerAppPort }}
