#!/usr/bin/env python3
"""Server that increments a counter each time it is accessed."""

import json
from http.server import SimpleHTTPRequestHandler

from pingpong_dbhandler import PingPongDataBaseHandler
from tcpserver import TCPServerLauncher


class PingPongRequestHandler(SimpleHTTPRequestHandler):
    """Serves the content of a specified log file and increments a counter."""

    def do_GET(self) -> None:  # noqa: N802
        """Handle GET request and serve the counter value."""
        response = json.dumps({"pongs": DB_CONNECTION.get_counter_value()})
        self.send_response(200)
        self.send_header("Content-type", "application/json")
        self.end_headers()
        self.wfile.write(response.encode())
        DB_CONNECTION.increment_counter_value()


if __name__ == "__main__":
    DB_CONNECTION = PingPongDataBaseHandler()
    DB_CONNECTION.increment_counter_value()
    TCPServerLauncher.run(int("{{.appPort}}"), PingPongRequestHandler)
