---
{{- with .Values}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{index .containerNames 0}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{index .containerNames 0}}
  template:
    metadata:
      labels:
        app: {{index .containerNames 0}}
    spec:
      containers:
        - name: {{index .containerNames 0}}
          image: "{{index .containerNames 0}}:latest"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          command:
            - "/bin/bash"
            - "-c"
            - "{{.tempScriptVolumeMountPath}}/{{index .containerNames 0}}"
          readinessProbe:
            httpGet:
              path: /
              port: {{.appPort}}
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: {{.sharedPersistentVolumeName}}
              mountPath: {{.sharedVolumeMountPath}}
            - name: {{.tempStartupScriptVolumeName}}
              mountPath: {{.tempScriptVolumeMountPath}}
              readOnly: true
      volumes:
        - name: {{.sharedPersistentVolumeName}}
          persistentVolumeClaim:
            claimName: {{.sharedPersistentVolumeClaimName}}
        - name: {{.tempStartupScriptVolumeName}}
          configMap:
            name: {{index .containerNames 0}}
            items:
              - key: {{index .containerNames 0}}
                path: {{index .containerNames 0}}
                mode: 0755
              - key: {{index .containerNames 1}}
                path: {{index .containerNames 1}}
                mode: 0755
{{- end}}
