---
{{- with .Values}}
{{- include "deployment.spec.base" $}}
    spec:
      {{- include "init.container.waitdb" $}}
      containers:
          {{- include "container.base" $}}
          {{- include "postgres.env" $}}
          ports:
            - containerPort: {{.appPort}}
          {{- include "probes.get" $}}
          {{- include "security.context" $}}
          {{- include "volumemounts.base" $}}
      {{- include "volumes.base" $}}
      terminationGracePeriodSeconds: 5
{{- end}}
