---
{{- with .Values}}
{{- template "deployment.spec.base" $}}
    spec:
      {{- template "init.container.waitdb" $}}
      containers:
          {{- template "container.base" $}}
          envFrom:
            - secretRef:
                name: {{index .databases.postgres.containerNames 0}}
          ports:
            - containerPort: {{.appPort}}
          {{- template "probes.get" $}}
          {{- template "security.context" $}}
          {{- template "volumemounts.base" $}}
      {{- template "volumes.base" $}}
      terminationGracePeriodSeconds: 5
{{- end}}
