apiVersion: v1
kind: Service
metadata:
  name: {{.Values.randomLogServerAppServiceName}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.randomLogServerAppName}}
  ports:
    - port: {{.Values.randomLogServerAppClusterPort}}
      protocol: TCP
      targetPort: {{.Values.randomLogServerAppPort}}
