---
containerNames:
  - todoappender
depValues:
  project-other:
    apps:
      postgres:
        - serviceName
        - appPort
        - containerNames
depValuesNoRoute:
  project:
    apps:
      backend:
        - dbTableName
