apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
spec:
  metrics:
  - name: cpu-usage
    initialDelay: 2m
    successCondition: result < 0.003
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(
            sum(
              rate(
                  container_cpu_usage_seconds_total{namespace="project-dev-jmetsola"}[2m]
              )
            )
          )
