---
{{- with .Values}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{index .containerNames 0}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{.serviceName}}
                port:
                  number: {{.clusterPort}}
{{- end}}
