---
{{- with .Values}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{index .containerNames 0}}
data:
  {{index .containerNames 0}}: |
    #!/bin/bash
    set -euo pipefail

    PYTHONPATH=/app /app/simple_server/simple_server.py \
    --port "{{.projectAppPort}}" \
    --picture-file "{{.randomPictureFileMountPath}}/{{.randomPictureFileName}}"
{{- end}}
