---
{{- with .Values}}
apiVersion: v1
kind: Service
metadata:
  name: {{.projectAppServiceName}}
spec:
  type: ClusterIP
  selector:
    app: {{index .containerNames 0}}
  ports:
    - port: {{.projectAppClusterPort}}
      protocol: TCP
      targetPort: {{.projectAppPort}}
{{- end}}
