#!/usr/bin/env python3

"""Starts a simple HTTP server that serves the content of a specified log file."""

from http.server import SimpleHTTPRequestHandler
from pathlib import Path

from tcpserver import TCPServerLauncher

LOG_FILE = Path("{{.logFileMountPath}}") / "{{.logFileName}}"


class LogRequestHandler(SimpleHTTPRequestHandler):
    """Request handler that serves the content of a log file."""

    def _get_log_content(self) -> str:
        with Path(LOG_FILE).open() as file:
            return file.read()

    def do_GET(self) -> None:  # noqa: N802
        """Handle GET requests by reading the log file and returning its content."""
        log_content = self._get_log_content().encode("utf-8")
        self.send_response(200)
        self.send_header("Content-type", "text/plain")
        self.end_headers()
        self.wfile.write(log_content)


if __name__ == "__main__":
    if not Path(LOG_FILE).exists():
        with Path(LOG_FILE).open("w") as file:
            file.write("\n")
    TCPServerLauncher.run(int("{{.appPort}}"), LogRequestHandler)
