#!/usr/bin/env python3

"""Generates and prints random strings."""

import os
import secrets
import string
import time
from datetime import datetime, timezone
from pathlib import Path

from pingpong_dbhandler import PingPongDataBaseHandler


class RandomStringPrinter:
    """Generate and print random strings."""

    @staticmethod
    def _generate_random_string(length: int = 12) -> str:
        letters = string.ascii_letters + string.digits
        return "".join(secrets.choice(letters) for _ in range(length))

    @staticmethod
    def run(logfile: str) -> None:
        """Print a random string every 5 seconds."""
        db_connection = PingPongDataBaseHandler()
        while True:
            random_string = (
                RandomStringPrinter._generate_random_string() + "\n"
                "Pings / Pongs: " + str(db_connection.get_counter_value())
            )
            timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
            with Path.open("{{.tempScriptVolumeMountPath}}/{{.informationFile}}") as f:
                contents = f.read()
            with Path(logfile).open("w") as f:
                f.write(
                    f"{os.environ['MESSAGE']}\n"
                    f"file contents: {contents}\n"
                    f"{timestamp} - {random_string}\n"
                )
            time.sleep(5)


if __name__ == "__main__":
    RandomStringPrinter.run(logfile="{{.logFileMountPath}}/{{.logFileName}}")
