---
on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      DOCKER_TOKEN:
        required: true
      DOCKER_USERNAME:
        required: true
    inputs:
      EXPORT_IMAGE_CACHE:
        type: boolean
        required: true

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: jkmetsola/dwk-deploy:${{ github.sha }}
      EXPORT_IMAGE_CACHE: "${{ inputs.EXPORT_IMAGE_CACHE }}"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: |-
          git config --global --add safe.directory \
            /home/runner/work/devopswithkubernetes/devopswithkubernetes
      - run: docker buildx create --name mybuilder --driver docker-container --use
        if: ${{ inputs.EXPORT_IMAGE_CACHE == true }}
      - run: |-
          echo "${{ secrets.DOCKER_TOKEN }}" \
          | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: |-
          tools/gh-workflows/generate_dot_env.sh
          .devcontainer/init/initscript.sh "$IMAGE_TAG"
      - run: |-
          docker push "$IMAGE_TAG"
        if: ${{ inputs.EXPORT_IMAGE_CACHE != true }}
