---
on: # yamllint disable-line rule:truthy
  delete:
  push:

jobs:
  build-container:
    uses: ./.github/workflows/build.yaml
    with:
      EXPORT_IMAGE_CACHE: false
    secrets:
      DOCKER_TOKEN: "${{ secrets.DOCKER_TOKEN }}"
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"

  build-container-and-export-cache:
    uses: ./.github/workflows/build.yaml
    with:
      EXPORT_IMAGE_CACHE: true
    secrets:
      DOCKER_TOKEN: "${{ secrets.DOCKER_TOKEN }}"
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"

  deploy-project:
    runs-on: ubuntu-latest
    name: Deploy a project
    needs: build-container
    strategy:
      matrix:
        job: [project, project-other, static-code-check]
    container:
      image: jkmetsola/dwk-deploy:${{ github.sha }}
      options: --user=root
      env:
        GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/configure-env

      - run: .devcontainer/git-hooks/pre-commit.sh
        if: matrix.job == 'static-code-check'

      - name: Delete branch namespace
        if: |
          github.event_name == 'delete' &&
          (matrix.job == 'project' || matrix.job == 'project-other')
        uses: ./.github/actions/delete
        with:
          project: ${{ matrix.job }}

      - name: Deploy branch
        if: |
          github.event_name == 'push' &&
          (matrix.job == 'project' || matrix.job == 'project-other')
        uses: ./.github/actions/release
        with:
          project: ${{ matrix.job }}
