---
name: Execute action in container.

on:
  delete:
  push:

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: jkmetsola/dwk-deploy:${{ github.sha }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: |-
          tools/gh-workflows/generate_dot_env.sh
          .devcontainer/init/initscript.sh "$IMAGE_TAG"
      - run: |-
          echo "${{ secrets.DOCKER_TOKEN }}" \
          | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: |-
          docker push "$IMAGE_TAG"

  deploy-project:
    runs-on: ubuntu-latest
    name: Deploy a project
    needs: build-container
    strategy:
      matrix:
        job: [project, project-other]
    container:
      image: jkmetsola/dwk-deploy:${{ github.sha }}
      options: --user=root
      env:
        GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure-env
      - name: Delete branch namespace
        if: ${{ github.event_name == 'delete' }}
        uses: ./.github/actions/delete
        with:
          project: ${{ matrix.job }}
      - name: Deploy branch
        if: ${{ github.event_name == 'push' }}
        uses: ./.github/actions/release
        with:
          project: ${{ matrix.job }}
