---
name: Release application

on:
  push:

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: |-
          tools/gh-workflows/generate_dot_env.sh
          .devcontainer/init/initscript.sh \
          jkmetsola/dwk-deploy:${{ github.sha }}
      - run: |-
          echo "${{ secrets.DOCKER_TOKEN }}" \
          | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push jkmetsola/dwk-deploy:${{ github.sha }}

  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    needs: build-container
    defaults:
      run:
        shell: bash

    container:
      image: jkmetsola/dwk-deploy:${{ github.sha }}
      options: --user=root
      env:
        GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

    steps:
      - uses: actions/checkout@v4
      - run: tools/gh-workflows/authenticate_service_user.sh
      - run: gcloud --quiet auth configure-docker europe-north1-docker.pkg.dev
      - run: gcloud config set project dwk-gke-440513
      - run: gcloud config set compute/zone europe-north1-b
      - run: gcloud container clusters get-credentials dwk-cluster
      - run: tools/gh-workflows/generate_age_key.sh
      - run: |- # To avoid errors with git commands
          git config --global --add safe.directory \
            /__w/devopswithkubernetes/devopswithkubernetes
      - name: Build-Publish-Deploy
        run: |-
          tools/gh-workflows/generate_dot_env.sh
          tools/launch_project.sh project-other
